### ISSUE TITLE
📝. Steps of an Election

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard#100]
This is currently highlighted at the lower level in `electionguard-python` docs but should get migrated to this repository. 

See: https://electionguard-python.readthedocs.io/en/latest/

Pull from the step by step process in the python repository and create a non code version of these steps. This should highlight the basics of setting up and running an election. 

There are some temporary pages to help determine where this should be added
All the pages needed to be added to `docs/basics`

**Comment by KanhaKorgaonkar** [comment]
Hi! I would like to work on this please. Thanks!
