### ISSUE TITLE
Typos in docs/spec/1.0.0/3_Baseline_parameters.md

### ISSUE THREAD

**Issue by pereira** [microsoft/electionguard#103]
## Generic Issue

**Description**
Two typos in docs/spec/1.0.0/3_Baseline_parameters.md

L7: 
- Standard parameters for ElectionGuard begin with the largest 256-bit prime $q = 2256 − 189$. The hexadecimal representation of $q$ is as follows.
+ Standard parameters for ElectionGuard begin with the largest 256-bit prime $q = 2^{256} − 189$. The hexadecimal representation of $q$ is as follows.

L25:
- The hexadecimal representation of $q$ is as follows:
+ The hexadecimal representation of $p$ is as follows:

**Possible Solution**
See above

**Comment by rc-ms** [comment]
thank you! will make and push updates momentarily

**Comment by keithrfung** [comment]
Page removed
