### ISSUE TITLE
📝  Document JSON Schema

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard#104]
## Feature Request

Create a JSON schema for each of the models in the `electionguard-python` repository. Use this [mkdocs plugin](https://github.com/galamdring/mkdocs-json-schema-plugin) to display the schema in documentation for easy consumption. 

### Tasks

- [ ] Create folder `schema` of JSON Schema
    - Election
         - [ ] Manifest
         - [ ] CiphertextElectionContext
         - [ ] ElectionConstants
         - [ ] EncryptionDevice
    - Ceremony
        - [ ] GuardianRecord
        - [ ] LagrangeCoefficientsRecord
    - Ballot
        - [ ] SubmittedBallot
        - [ ] CiphertextBallot
        - [ ] PlaintextBallot
    - Tally
         - [ ] PlaintextTally
         - [ ] CiphertextTally
         - [ ] PublishedCiphertextTally (Until adjustments made)

- [ ] Document
    - Under a `Data Format` section, add brief description and then link to pages for each of the previous schemas as individual pages with a brief description and using the mkdocs plugin to display schema file. It should target https://www.electionguard.vote/spec/Data_Format/

**Comment by keithrfung** [comment]
As a sidenote, these can be broken up into individual pull requests instead of tackling this as a full issue.

**Comment by manoloesparta** [comment]
Can you assign me this? I would like to help

**Comment by keithrfung** [comment]
@manoloesparta Sure. It's a pretty big issue. Try and take a chunk at a time.

**Comment by melkyy** [comment]
Could you assign this one :)

**Comment by melkyy** [comment]
Ok I'm figure out how accomplish this, where I create the schema folder? inside of docs? or in the root of the project?

**Comment by keithrfung** [comment]
@melkyy We would absolutely love some help on this. Remember you don't have to do ALL of the schemas just any and getting started would be appreciated. 

I would make a `schema` folder within the `docs` folder. 

```
- docs / 
--- schema / 
------ example.schema.json
```

Each schema should be linked to from the Data Format page. 
https://www.electionguard.vote/spec/Data_Format/

An example would be:

```md
## Ballot

-  [SubmittedBallot](link_to_schema)
    A ballot that has been cast or spoiled/challenged. 

```
