### ISSUE TITLE
📝. Create Specification Badges Page

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard#112]
## Feature Request

Using shields, create a page within the Specification that displays ElectionGuard Badges. 

Navigation:
- Specification
    - Current
    - Badges <--
    - Other Versions

Under Badges.md, 
> # Badges
> For your convenience, these are some badges to add to your repository indicating the specification your code supports. 

Then list the badges with their shown image and a `code` line with a line that can be copy pasted. 

[![ElectionGuard Specification 0.85.0](https://img.shields.io/badge/🗳%20ElectionGuard%20Specification-0.85.0-green)](https://www.electionguard.vote)
`[![ElectionGuard Specification 0.85.0](https://img.shields.io/badge/🗳%20ElectionGuard%20Specification-0.85.0-green)](https://www.electionguard.vote)`

[![ElectionGuard Specification 0.95.0](https://img.shields.io/badge/🗳%20ElectionGuard%20Specification-0.95.0-green)](https://www.electionguard.vote)
`[![ElectionGuard Specification 0.95.0](https://img.shields.io/badge/🗳%20ElectionGuard%20Specification-0.95.0-green)](https://www.electionguard.vote)`

[![ElectionGuard Specification 1.0.0](https://img.shields.io/badge/🗳%20ElectionGuard%20Specification-1.0.0-yellow)](https://www.electionguard.vote)
`[![ElectionGuard Specification 1.0.0](https://img.shields.io/badge/🗳%20ElectionGuard%20Specification-1.0.0-yellow)](https://www.electionguard.vote)`

There should be a badge for all versions. 1.0.0 should be shown in yellow. 
These badges should replace the badges on each of the specification pages.

**Comment by abxhr** [comment]
I would love to work on this! 🚀

If I'm not wrong, the new `badges.md` file should be placed inside `electionguard/docs/spec` with all the versions available?
