### ISSUE TITLE
misspelling on Code page of word "verifiable" as "veriable"

### ISSUE THREAD

**Issue by jeffshannon** [microsoft/electionguard#12]
## Generic Issue

- [x] Ensure this issue is not a bug report or feature request

**Description**
On "Code" page of this github repository there's a misspelling in the project description. I don't believe this is part of the source tree.

> ElectionGuard is a set of open source software components that can be used to create and publish end to end **veriable** elections as well create a publishable artifact for ballot comparison audits.

**Possible Solution**

> ElectionGuard is a set of open source software components that can be used to create and publish end to end **verifiable** elections as well create a publishable artifact for ballot comparison audits.

**Additional context/Screenshots**
None.

**Comment by keithrfung** [comment]
Already resolved in previous PR. Thanks for your support!
