### ISSUE TITLE
📝 Create Structures and Processes Section

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Using the following documents, create a `Structure_and_Processes.md` section. The pdf is provided for those without word but the docx is the source of truth.
docx: [EG-SP3.docx](https://github.com/microsoft/electionguard/files/7286830/EG-SP3.docx)
pdf: [EG-SP3.pdf](https://github.com/microsoft/electionguard/files/7286831/EG-SP3.pdf)

### Possible Implementation

- Create a `Structure_and_Processes.md` under `concepts` folder
- Add to navigation. This should be the first page in the Concepts section before Election_Manifest
- Title or H1 should be Structures and Processes, any other headings should be H2 or lower
- Directly convert all text exactly as is. 
- Convert all tables and equations using mkdocs plugins. On rare exceptions use screenshots of the document. This should be **minimized**. The preference is in markdown. 

### Anything else?

These will be helpful:
https://squidfunk.github.io/mkdocs-material/reference/diagrams/
https://squidfunk.github.io/mkdocs-material/reference/mathjax/
https://squidfunk.github.io/mkdocs-material/reference/data-tables/

**IMPORTANT**
Ensure that @benaloh is tagged on the review and include copious screenshots in the pull request.

**Comment by inomag** [comment]
Hi @keithrfung. Can I work on this task?

**Comment by keithrfung** [comment]
@inomag of course.

**Comment by inomag** [comment]
Hi @keithrfung, I have created the Tables using HTML tag, equations using Mathjax, and a bit of Latex & diagrams using Mermaid. Everything is almost the same as that in the pdf and doc, but I am facing some difficulties in subscript & superscript in mermaid diagram
![screencapture-127-0-0-1-8000-concepts-Structure-and-Processes-2021-10-06-16_36_55](https://user-images.githubusercontent.com/66073063/136191958-a7fbe847-dbb9-4c5d-8f3e-7e1568b3202c.jpg)
![Capture](https://user-images.githubusercontent.com/66073063/136192045-0a1adcf4-6c7a-4fc2-b910-44fade0fca44.JPG)
![Capture1](https://user-images.githubusercontent.com/66073063/136192048-3f67b2cd-7ac4-4d2b-819c-18868e33baf3.JPG)
s.

**Comment by keithrfung** [comment]
@inomag Wow this is looking great!

I have a fix for you!

Add this to `mkdocs.yml`
![Screen Shot 2021-10-06 at 4 45 30 PM](https://user-images.githubusercontent.com/10125297/136280544-2a7b7b34-b68c-41f8-acfe-ff1bfeaa9be8.png)

This "loose" option allows html scripts within the mermaid documentation. 

Then you can do this:
```mermaid
flowchart TD
    test1["A<sup>2</sup>"] --> test2["A<sub>2</sub>"]
```

![Screen Shot 2021-10-06 at 4 46 30 PM](https://user-images.githubusercontent.com/10125297/136280679-03372b95-e550-4b3b-9f3f-5a8802514d27.png)
