### ISSUE TITLE
🎨  Create custom spec admonitions

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Using custom admonitions create a green admonition with an exclamation mark icon. This should have an entirely green box so this can be used to mimic the specification pdf which has highlighted green text. 

See the squidfunk documentation for more information. 
https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions

**Comment by KanhaKorgaonkar** [comment]
Hi I would like to work on this please. Thanks!

**Comment by KanhaKorgaonkar** [comment]
Please let me know where the admonition files go in the repository. Thanks!

**Comment by keithrfung** [comment]
Yes and the squidfunk link that I have on the issue actually links to this page:
https://squidfunk.github.io/mkdocs-material/customization/#adding-assets

we have a similar `stylesheets` folder for the custom css

**Comment by KanhaKorgaonkar** [comment]
Thanks! @keithrfung, also, where is the specification pdf please?

**Comment by KanhaKorgaonkar** [comment]
Hey, I am testing the admonition in a md file, but they don’t seem to show up on GitHub. Are they supposed to show up in the GitHub preview?

**Comment by keithrfung** [comment]
@KanhaKorgaonkar Sorry, I missed the first message. 

The admonitions are a mkdocs plugin which is part of the mkdocs material tool we use. If you want to test, run `make serve` on the repository.

**Comment by KanhaKorgaonkar** [comment]
Hey I may not be able to do this, so unassigning myself. Extremely sorry for the inconvenience. 😭

**Comment by keithrfung** [comment]
@ikechigriffith Of course. Have at it!
