### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by weaversa** [microsoft/electionguard#17]
## Generic Issue

- [X ] Ensure this issue is not a bug report or feature request

**Description**
The following sentence from README.md is missing a word. 

“For instance, the ballot marking device could be replaced with an optical-scanner produces verifiable encrypted records, ...”

**Possible Solution**
Add ‘that’

For instance, the ballot marking device could be replaced with an optical-scanner that produces verifiable encrypted records, ...

**Comment by keithrfung** [comment]
Text was changed in another PR.
