### ISSUE TITLE
Follow up from Fulton, Wisconsin ElectionGuard testing?

### ISSUE THREAD

**Issue by bikeoid** [microsoft/electionguard#18]
There were many news articles and a blog post about the February 18, 2020 ElectionGuard test in Fulton, Wisconsin, but nothing since.   I've searched for a followup post about those results, or if ElectionGuard will make its way into any future election technology?

**Comment by rc-ms** [comment]
Hello @bikeoid and thanks for your question.  We continue development of ElectionGuard (see our latest release of the full [ElectionGuard "stack" in Python](https://github.com/microsoft/electionguard-python). We have more coming soon, and hope to have a place where we'll be making these announcements in future.  We are very excited about the future of ElectionGuard and end-to-end verifiability in general, as indicated in our comments for the new VVSG 2.0 Voting System Requirements
