### ISSUE TITLE
🐞 Regenerate Sample Data 

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Sample data needs to be regenerated using the new tooling. The preferred method is to use the python tooling to generate this data. The `hamilton-general` data is missing the lagrange coefficients. The other sample data ((`full`, `small`, and `minimal`). is using an old format and should be regenerated.

 
### Possible Implementation

Update documentation on ElectionGuard site to showcase `0.95.0` version of an Election Record Package (`record.zip`). The files for the zip will have to be generated likely from python and manually packaged. This should include big numbers as hex representation and include lagrange coefficients mentioned in #181. 

**NOTE:** This should also include sample data zip (this should be named something like `private` or `secret` or `source`) that includes PlaintextBallots and the like for testing Upload ballot task. This is not the election record so should be zipped separately to avoid confusion since this data is **NOT PUBLIC** but merely for developer examples.

The documentation should showcase the new data and how it can be used for results and verification sites. The format of the directory will have to be explained in the documentation.
See 
https://www.electionguard.vote/spec/Data_Format/
https://www.electionguard.vote/develop/Sample_Data/

The Sample Data page is also 
1. missing a manifest of the cast/spoiled ballots
2. uses the word `artifacts` instead of `record`
3. Does not include Lagrange coefficeints.

**Comment by JohnLCaron** [comment]
it would be nice if the sample data was a complete "election record" exactly as it is published/exported from the reference implementation, maybe with a zip / tar.gz option.

**Comment by keithrfung** [comment]
@JohnLCaron the sample data should meet this now. There is another issue with the tar.gz option.
