### ISSUE TITLE
✨  Versioning Serialization not just Specification

### ISSUE THREAD

**Issue by JohnLCaron** [microsoft/electionguard#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

A serialization version number would allow smooth upgrading of the serialization format, and prevent silent failures of processing the election record. Consider adding that to (perhaps) the CiphertextElectionContext.

The serialization version number is a technical implementation detail, set by the software library. 

### Anything else?

The Manifest is for a specific election, and would be created and maintained by election officials. The version there I think would reflect the Manifest object model and perhaps the manifest itself as it evolves for that specific election.

The spec_version may also be separate, since the electionguard specification does not actually describe the Manifest object model (or the specification format). So the object model and spec_version might evolve separately from the serialization version, and perhaps should all be separate.

**Comment by ramsdell** [comment]
I enthusiastically agree with this suggestion and agree that the serialization version number belongs in the manifest.

**Comment by rc-ms** [comment]
thanks all! We are in agreement on the go-forward. We will specify an SDK version that will map to specific necessary supporting repo releases. I'm going to close this issue since it lumps two issues together best handled as separate tasks.
