### ISSUE TITLE
🐞 Sample data are inconsistent

### ISSUE THREAD

**Issue by JohnLCaron** [microsoft/electionguard#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

electionguard/data/0.95.0/sample data 

uses base10 or base16 for encoding bigintegers
sometimes use current primes, sometimes previous ones

```
                             bigint   constants
                             --------  ------------ 
full                         base10   standard
hamilton-general             base16   ?
minimal                      base10  previous
small                        base10  previous
```

### Environment

```markdown
- OS:
```

**Comment by keithrfung** [comment]
That's super interesting. They were all generated with the same codebase and same primes recently. Is this referring to it off what's include in the zip or what's included in the raw folders?

**Comment by keithrfung** [comment]
@JohnLCaron can you double check me and look and see how we're serializing in Python to doublecheck there isn't something fishy about the BigInt serialization in terms of `base16` vs `base10`. They should all be using the new primes and `base16` aka hex for serialization.

**Comment by keithrfung** [comment]
We can likely do something post 1.4 where we rebuild the entire set of sample data at that juncture and only include the manifests in here. I think that's the simplest solution.

**Comment by JohnLCaron** [comment]
ok, the constants seem ok now.

however, the coefficients.json files seem wrong, and different that what I get when i run

my run :+1: 
````
{
  "coefficients": {
    "1": {
      "data": "05"
    },
    "2": {
      "data": "FFE7"
    },
    "3": {
      "data": "0A"
    },
    "4": {
      "data": "FFEC"
    },
    "5": {
      "data": "01"
    }
  }
}
````

what i see in electionguard/data/0.95.0/sample/full:


````

**Comment by JohnLCaron** [comment]
Since 0.95 data are now inconsistent with 1.0, Im removing my tests on  0.95 data and closing this issue.
