### ISSUE TITLE
✨ Create Events section in website to track and host in-person and virtual events

### ISSUE THREAD

**Issue by rc-ms** [microsoft/electionguard#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

ElectionGuard is a community effort, and beyond the code development itself there are also in-person and virtual events people might want to be made aware of and attend. This issue will create an events feature branch to share an interim calendar among participants in planning for some upcoming events; when finalized schedules will be published on an as-needed basis as additional events.

### Possible Implementation

This is a very low-impact change to the pages of the mkdocs website

**Comment by nawed2611** [comment]
Hey, is this issue open to work on?

**Comment by rc-ms** [comment]
hello there @nawed2611 thank you for your offer but i'll be checking this in soon. it's just a content change mostly
