### ISSUE TITLE
Project description has a typo

### ISSUE THREAD

**Issue by brendan-src** [microsoft/electionguard#25]
## Generic Issue

The project description has a typo.

**Description**
ElectionGuard is a set of open source software components that can be used to create and publish end to end **veriable** elections as well create a publishable artifact for ballot comparison audits.

**Possible Solution**
ElectionGuard is a set of open source software components that can be used to create and publish end to end verifiable elections as well create a publishable artifact for ballot comparison audits.

**Comment by echumley-msft** [comment]
Thanks for pointing this out, typo fixed.
