### ISSUE TITLE
🐞 Fix Schema for votes_allowed and number_elected

### ISSUE THREAD

**Issue by lprichar** [microsoft/electionguard#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

votes_allowed can be null or zero

### Expected Behavior

votes_allowed must be an integer, non-null and greater than 0
number_elected must be an integer, greater than 0

### Environment

```markdown
- OS:
```

**Comment by abxhr** [comment]
@lprichar I would love to work on this issue 🚀
