### ISSUE TITLE
Remove Hacktoberfest Links

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard#42]
Hacktoberfest is over and it's time for some cleanup.

1. This page will need deleting.
https://github.com/microsoft/electionguard/blob/main/docs/Hacktoberfest.md
2. The overrides contain a banner that will need to be cleaned up.
3. The mkdocs file will need to have the links removed.

**Comment by yeltsinxyz** [comment]
Sorry for not asking first. As it was simple, I did before asking 😦
