### ISSUE TITLE
Add Roadmap

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard#49]
Users and contributors of ElectionGuard want to know what's coming next. It's time to make a roadmap so users know what is coming next.  This should include what we have already done and what is coming up next. 

This should be a page in the electionguard site but also mentioned on the ReadMe.md

**Comment by rc-ms** [comment]
adding intro and strategic overview

**Comment by kcmd** [comment]
Thank you for this. This project is bound to start getting a lot of attention (if not already) in light of recent election integrity concerns. Regardless if one views such as a valid concern (an understandable position), this project has the potential to solve many challenges... if the features, accessibility, diversity of use-cases and audits eventually lead to broad adoption. Having a roadmap, milestones and evolving vision all help.
