### ISSUE TITLE
Add a discussion link to the website and to the ReadMe

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard#51]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We'd like the Discussions page to be more evident to new users so they know that's the place to discuss questions regarding the specification.

**Describe the solution you'd like**
- Add a link in the Contributing section of the Readme.md
- Add a link in the Contributing section of the index.md
- Friendly wording to encourage people to asks questions and make suggestions

This would be the link: https://github.com/microsoft/electionguard/discussions

**Comment by 96RadhikaJadhav** [comment]
@keithrfung Can I work on the issue? Also could you please explain exactly where and how much lines of wording have to add?
