### ISSUE TITLE
Implementations documentation has everything except  "Web-API" in archived section 

### ISSUE THREAD

**Issue by JohnLCaron** [microsoft/electionguard#53]
In docs/guide/Implementations.md, everything except "Web-API" is under "Archived". At least the "Verifiers" should not be. I can send PR if I know which others are not archived.

**Comment by rc-ms** [comment]
Thanks for the heads up. We're cleaning up and reorganizing but verifier contributions should absolutlely be preserved and showecased

**Comment by keithrfung** [comment]
Outdated.
