### ISSUE TITLE
🎨 Improve or Remove Icon in top left corner

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard#98]
![Screen Shot 2021-08-05 at 1 38 29 PM](https://user-images.githubusercontent.com/10125297/128395932-bce0d469-8851-4612-bafa-4496f47cccfc.png)

The icon does not show up alongside the text in a very discernible way. This icon could either be changed or enlarged or perhaps removed to provide a cleaner look. 

Squidfunk reference material
https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/

**Comment by Jayita10** [comment]
![Screenshot (327)](https://user-images.githubusercontent.com/85472715/134291966-837059e3-ac7f-4014-a773-94b40162662b.png)

Will it be okay? I have reduced the space between icon and title.

**Comment by keithrfung** [comment]
@Jayita10 Missed that but this sounds like a great fix!

**Comment by Jayita10** [comment]
There are some html and css extensions present which are not the part of this repository. Please suggest what would be the possible location/repository to get these files

**Comment by keithrfung** [comment]
@Jayita10 Are you looking at the code inspect? This is built with `mkdocs` which converts markdown into a static webpage. 

Our specific theme allows customization, there is some documentation for it here
https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#configuration

**Comment by rktejesh** [comment]
@keithrfung Is this issue still up for grabs?

**Comment by SteveMaier-IRT** [comment]
Reviewed the current application with Lee and we found that this is resolved.
